### ISSUE TITLE
Docker api version 1.41

### ISSUE THREAD

**Issue by alecnotthompson** [fussybeaver/bollard#158]
Hello! Looks like a cool library! 

Is there any work being put into supporting the newer api version? Is there a list of work that needs to be done in order to do so?

**Comment by fussybeaver** [comment]
The library currently supports v1.41 - we generate rust models from the upstream openapi specification: https://github.com/fussybeaver/bollard/blob/master/codegen/pom.xml#L22 . 

The surface API is still manually maintained, because some endpoints need special handling, hence parts of the docker swarm API are not implemented - if there is demand for adding something that's missing, I'm happy to add it.

**Comment by alecnotthompson** [comment]
Cool! Thanks for the response. I asked because of [this line in the documentation](https://docs.rs/bollard/0.10.1/bollard/#version):

```
The Docker API is pegged at version 1.40. The library also supports version negotiation, to allow downgrading to an older API version.
```
