### ISSUE TITLE
Cargo fmt isn't enforced in CI

### ISSUE THREAD

**Issue by edmorley** [fussybeaver/bollard#212]
When editing files locally, several times I've had larger than expected diffs, since my IDE's "format on save" has ended up running `cargo fmt` on files that don't currently match the expected Rust file formatting.

Checking the CI configs, I see `cargo fmt` isn't currently enforced.

To do so, something like the following should be run:
`cargo fmt -- --check --verbose`

**Comment by fussybeaver** [comment]
I think it would be useful to add that. However, I don't think the code generated by the openapi file is `cargo fmt` compatible, so one would need to skip that.

**Comment by Stargateur** [comment]
> I think it would be useful to add that. However, I don't think the code generated by the openapi file is `cargo fmt` compatible, so one would need to skip that.

What do you mean by not compatible ? cargo fmt fail to parse it ? if you push generate file it's *generally* recommanded to be readable and so fmt it is a good idea. It's even the default of bindgen. After all if you decide to push the file it's not because it's should be readded ? if not why push it ? Only when the api change the fmt file would change but that is expected.

Thus I have no idea about detail on this case It's may be a bad thing on this case, just randomly read this issue, I go back into shadow.

**Comment by fussybeaver** [comment]
Thanks for chiming in, maybe I'm not clear enough.

What I mean is, making cargo fmt mandatory is fine for the bollard source, but not for the openapi codegen - cargo fmt works on the generated files, but the templating for the openapi spec hasn't been developed enough to output rust formatted perfectly, that cargo fmt would accept.

Maybe it's another ticket to do that work though...
