### ISSUE TITLE
fix type of BuildCache CreatedAt and LastUsedAt

### ISSUE THREAD

**Issue by mdonoughe** [fussybeaver/bollard#89]
I contributed some code to stepchowfun/docuum to use Bollard instead of invoking the Docker CLI, and almost immediately after releasing this version it was discovered that Bollard cannot parse the output of /system/df when if the user has been using BuildKit (stepchowfun/docuum#78).

Bollard is following exactly the Docker documentation, which was apparently wrong in this case (moby/moby#41264). The documentation was fixed in moby/moby#41267, but possibly the URL where Bollard pulls the API specifications from won't be updated until Docker 20.03 ships (I just checked and it hadn't been), and even then Bollard will need a rebuild because the generated code is in [codegen/target/generated-sources/src/models.rs](https://github.com/fussybeaver/bollard/blob/e3e0565b3e367fdf9fe838760006d61f1403e775/codegen/target/generated-sources/src/models.rs#L190-L196).

I don't know if you want to pick up the new spec from the repo now or if you want to wait until the spec is updated on the website. In the mean time, Docuum has gone back to using Docker CLI.

**Comment by fussybeaver** [comment]
Thanks for the detailed write-up and reporting this upstream. 

I'm not against referencing the swagger YAML in a tag of moby's Github instead of the website, and regenerating the API stubs, though I'd want the tag somehow reflected in the versioning of the `bollard-stubs` repository. Perhaps, that could be done using an `alpha` release.
